from typing import Any, Optional, Self

from cn.snowskystudio.newgame.test.Logger import Logger


class Configuration:
    logger: Logger
    config_file: str
    config: dict[str, Any]
    
    def __init__(self, config_file: str, logger: Optional[Logger]=None) -> Self: ...
    
    def set_logger(self, logger: Logger) -> None: ...
    
    def init(self) -> None: ...
    
    def load(self) -> None: ...
    
    def save(self) -> None: ...
    
    def is_debug(self) -> bool: ...
    
    def set_debug(self, debug) -> None: ...
    
    def set(self, key, value) -> None: ...
    
    def get(self, key) -> Any: ...
