class ResourceLocation:
    id: str
    path: str
    full_path: str
    name: str
    
    def __init__(self, _id: str, path: str): ...
    
    def __str__(self): ...
    
    def __repr__(self): ...
    
    def __eq__(self, other): ...
    
    def get_id(self): ...
    
    def get_path(self): ...
    
    def get_full_path(self): ...
    
    def get_name(self): ...
